### PR TITLE
Bug fixes

### LINKED ISSUE #3: Bug - title of incident needs to be capped to 255 chars for Gitlab
Op should limit issue title during creation to 255 chars

### PR DESCRIPTION
**Pull request by tw5033**
Closes #3 #4 #5. 
Changes
- Added validation to issue title prompt
- Fixed PagerDuty initialization during incident creation
- Prints user friendly message when no issues are available to be updated

### CODE REVIEW

**Comment by CalHoll** [comment]
This looks good, I like readability improvements so definitely bring those in and I like when prettier fixes things automatically for us but we should come up with a better way of bringing in those changes since it's a little cluttered and difficult to review the things that make changes to the logic.

Maybe in the future if you realize something needs to be prettified just run prettier on the whole src directory and make that a commit that's separated from the logic changes.

File: prompts/index.js [hunk 1]
```diff
@@ -61,7 +49,15 @@ const incidentStartPrompts = [
...
+    message: `\n⚠️  Please describe the incident: ${secondary(
+      '(Maximum 255 characters)'
+    )}`,
+    validate: input => {
+      if (input.length < 255) {
+        return true
+      }
+      return 'There is a 255 character limit!'
+    },
   },
```
Comment (CalHoll) [inline prompts/index.js]: Validate is going away, so you can merge this in but do a sdk 2 update after
